version: "3.9"

services:
  toil:
    build:
      context: .
      dockerfile: toil/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock      
      - /tmp/:/tmp
    tty: true
    stdin_open: true
  toil-omniverse-ext:
    build:
      context: .
      dockerfile: toil-omniverse-ext/Dockerfile
    volumes:
      - ~/Documents/Kit/shared/exts/:/exts
