FROM alpine:latest
RUN apk update && apk add xfce4 xfce4-terminal xrdp

RUN xrdp
# RUN echo "exec firefox" > ~/.xinitrc && chmod +x ~/.xinitrc
# CMD ["x11vnc", "-create", "-forever"]





# FROM alpine:3.14

# WORKDIR /omniverse
# COPY omniverse-launcher-linux.AppImage omniverse-launcher

# RUN x
# RUN ls -l
# RUN ./omniverse-launcher