/vis/open OGL
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume

/vis/viewer/set/style surface
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

/gun/particle e-
#/gun/direction 0 0 0
#/gun/position 0 0 0
#/gun/energy 10 keV
#/run/beamOn 10
#/vis/vtk/export obj g4